# Site Build Settings

# Jekyll-paginate-v2 configuration
#  pagination:
#   enabled: true
#   per_page: 6
#   permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true

# jekyll-paginate configuration
# paginate:            6

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [
  # native plugins
  jekyll-sitemap,
  jekyll-feed,
  jekyll-seo-tag
]

title:		           'Luong Restoration & Rangeland Ecology Lab       '  
description:	         'University of California, Berkeley - Environmental Science, Policy and Management'
author:              'Design by Eli at Eliengine.com, Curated by Justin Luong'
# _config.yml

# Use a STRING here so plugins like jekyll-seo-tag are happy
logo: /assets/img/ucbseal.png

header_logo:
  src: /assets/img/ucbseal.png
  alt: "Luong Lab badge"
  width: 100
  height: 100


# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
