# Change to true for Disqus comments
# This would be the main block for adding subpages


disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-112060364-1'

menu:
  - name: CV
    path: 'menu'      # Blank means root | root = cv.html
    url: 'cv.html'

    
  - name: 'Publications'
    path: 'menu'   # = /menu/publications.html
    url: 'publications.html'
 

  - name: 'Current Research'
    path: 'menu'
    submenu:
    - name: 'Current Research'
      url:  'currentresearch.html'
    - name: 'Past Research'
      url:  'pastresearch.html'

   
  - name: 'California GRASS-Net'
    path: 'menu'
    submenu: 'aboutgrassnet.html'
    - name: 'About GrassNet'     #Home and first subpage
      url:  'aboutgrassnet.html'
    - name: 'Get Involved'       #Middle subpage
      url:  'getinvolved.html'
    - name: 'Resources'          #Last subpage
      url:  'resources.html'

    
  - name: 'People'
    path: 'menu'
    submenu:
      - name: 'Justin Luong'
        url:  'justinluong.html'
      - name: 'Current Lab Associates'
        url:  'currentpeople.html'
      - name: 'Lab Alum'
        url:  'labalum.html'

    
  - name: 'Art & Science'
    path: 'menu'
    submenu:
      - name: 'Illustrated Summaries'
        url: 'illustratedsummaries.html'
      - name: 'Infographics'
        url: 'infographics.html'
    #removing parent URL links dropdown


    
  - name: 'Contact'
    path: 'menu'
    url: 'contact.html'

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/justinluong/'}
- {icon: 'youtube', link: 'https://www.youtube.com/channel/UC-3p5ABk3vPzAE80evNdfYg'}
- {icon: 'researchgate', link: 'https://www.researchgate.net/profile/Justin-Luong'}
- {icon: 'envelope', link: 'mailto:jluong4@ucsc.edu'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
 
